export const cityNames: string[] = [
  "afton",
  "albertville",
  "andover",
  "anoka",
  "apple valley",
  "arden hills",
  "belle plaine",
  "bethel",
  "birchwood village",
  "blaine",
  "bloomington",
  "brooklyn center",
  "brooklyn park",
  "buffalo",
  "burnsville",
  "carver",
  "centerville",
  "champlin",
  "chanhassen",
  "chaska",
  "circle pines",
  "columbia heights",
  "coon rapids",
  "corcoran",
  "cottage grove",
  "crystal",
  "dayton",
  "deephaven",
  "delano",
  "dellwood",
  "eagan",
  "east bethel", // not on map?
  "eden prairie",
  "edina",
  "grey cloud island",
  "elko new market",
  "excelsior",
  "falcon heights",
  "farmington",
  "forest lake", // did not work
  "fridley",
  "gem lake",
  "golden valley",
  "grant",
  "greenfield",
  "greenwood",
  "ham lake",
  "hampton",
  "hanover",
  "hastings",
  "hilltop",
  "hopkins",
  "hugo",
  "independence",
  "inver grove heights",
  "jordan",
  "lake elmo",
  "lake saint croix beach",
  "lakeland",
  "lakeland shores",
  "lakeville",
  "landfall",
  "lauderdale",
  "lexington",
  "lilydale",
  "lino lakes",
  "little canada",
  "long lake",
  "loretto",
  "mahtomedi",
  "maple grove",
  "maple plain",
  "maplewood",
  "marine on saint croix",
  "medicine lake",
  "medina",
  "mendota",
  "mendota heights",
  "minneapolis",
  "minnetonka",
  "minnetonka beach",
  "minnetrista",
  "monticello",
  "mound",
  "mounds view",
  "new brighton",
  "new hope",
  "new prague",
  "new trier",
  "newport",
  "north oaks",
  "north saint paul",
  "oak grove",
  "oakdale",
  "orono",
  "osseo",
  "pine springs",
  "plymouth",
  "prior lake",
  "ramsey",
  "richfield",
  "robbinsdale",
  "rogers",
  "rosemount",
  "roseville",
  "saint anthony",
  "saint bonifacius",
  "saint francis",
  "saint louis park",
  "saint marys point",
  "saint michael",
  "saint paul",
  "saint paul park",
  "savage",
  "shakopee",
  "shoreview",
  "shorewood",
  "south saint paul",
  "spring lake park",
  "spring park",
  "stillwater",
  "sunfish lake",
  "tonka bay",
  "vadnais heights",
  "vermillion",
  "victor",
  "wayzata",
  "west saint paul",
  "white bear lake",
  "willernie",
  "woodbury",
  "woodland",
];
